## Random Forest Classification Algorithm

### Step 1: Importing Necessary Libraries

In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Social_Network_Ads.csv")

In [3]:
data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

### Step 2: Applying Categorical Column and Unwanted Column

In [4]:
data= pd.get_dummies(data,dtype=int,drop_first=True)

In [5]:
data

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
# Axis =  1 --> Column wise delete
# Axis = 0 ---> Row wise delete
data = data.drop("User ID",axis = 1)

In [7]:
data

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [8]:
data["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
data.shape  #rows, columns

(400, 4)

### Step 3: To Split Input and Output Variables

In [10]:
Independent = data[['Gender_Male','Age','EstimatedSalary']]

In [11]:
Dependent = data[['Purchased']]

In [12]:
Independent

     Gender_Male  Age  EstimatedSalary
0              1   19            19000
1              1   35            20000
2              0   26            43000
3              0   27            57000
4              1   19            76000
..           ...  ...              ...
395            0   46            41000
396            1   51            23000
397            0   50            20000
398            1   36            33000
399            0   49            36000

[400 rows x 3 columns]

In [14]:
Dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

### Step 4: To Split Train and Test Values

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Independent, Dependent, test_size = 0.30, random_state = 42)

In [16]:
X_train.shape

(280, 3)

In [17]:
X_test.shape

(120, 3)

In [18]:
y_train

     Purchased
157          0
109          0
17           1
347          1
24           1
..         ...
71           0
106          0
270          0
348          0
102          0

[280 rows x 1 columns]

In [19]:
y_test

     Purchased
209          0
280          1
33           0
210          1
93           0
..         ...
60           0
79           0
285          1
305          0
281          0

[120 rows x 1 columns]

### Step 5: To choose the Algorithm and learn

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
Classifier = RandomForestClassifier(n_estimators=150,criterion='entropy',random_state=0)

In [23]:
Classifier

RandomForestClassifier(criterion='entropy', n_estimators=150, random_state=0)

In [24]:
Classifier.fit(X_train, y_train)

C:\Users\RAVISANKAR\AppData\Local\Temp\ipykernel_1716\3608353714.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  Classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=150, random_state=0)

In [25]:
y_pred = Classifier.predict(X_test)

### Step 6: To Find the Confusion Matrix of the Model

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
confusion_matrix(y_test,y_pred)

array([[67,  6],
       [ 7, 40]], dtype=int64)

### Step 7: To find the Classification_report

In [28]:
from sklearn.metrics import classification_report

In [29]:
Clf_report = classification_report(y_test, y_pred)

In [30]:
Clf_report

'              precision    recall  f1-score   support\n\n           0       0.91      0.92      0.91        73\n           1       0.87      0.85      0.86        47\n\n    accuracy                           0.89       120\n   macro avg       0.89      0.88      0.89       120\nweighted avg       0.89      0.89      0.89       120\n'

### Step 8: Test the Model using Values

In [32]:
Gender = int(input("Enter you gender (Male: 1, Female: 0): "))
Age = int(input("Enter you Age: "))
Estimated_Salary = int(input("Enter your Estimated Salary: "))

Classifier.predict([[Gender, Age, Estimated_Salary]])

Enter you gender (Male: 1, Female: 0):  1
Enter you Age:  35
Enter your Estimated Salary:  135000

C:\a\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

### Step 9:To save the Model

In [33]:
import pickle

In [34]:
filename="RFC.pkl"

In [35]:
pickle.dump(Classifier,open(filename,'wb'))

In [37]:
loaded_model=pickle.load(open("RFC.pkl",'rb'))

In [40]:
result=loaded_model.predict([[Gender,Age,Estimated_Salary]])

C:\a\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [41]:
result

array([1], dtype=int64)